// @flow
export const AUTH_INIT = "AUTH_INIT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_EXPIRED = "AUTH_EXPIRED";
export const AUTH_NOT_EXPIRE = "AUTH_NOT_EXPIRE";

export const AUTH_REQUEST_PROFILE = "AUTH_REQUEST_PROFILE";
export const AUTH_RECEIVE_PROFILE = "AUTH_RECEIVE_PROFILE";

export const SIGNUP_INIT = "SIGNUP_INIT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNUP_LOGOUT = "SIGNUP_LOGOUT";
